name: Coupon Scraper (A-G)

on:
  schedule:
    - cron: "0 0 * * 1" # Monday at midnight
  workflow_dispatch: # Manual trigger option

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Run partial scraper (A-G)
        run: node scraper/runner.js
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          LETTERS: "a,b,c,d,e,f,g"
          CONCURRENT_DOMAINS: 3 # Reduce if hitting rate limits
          BATCH_SIZE: 3
